name: Update LeetCode Stats
on:
  schedule:
    - cron: "0 0 * * *"  # Aggiorna ogni giorno a mezzanotte
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update LeetCode Stats
        uses: DenverCoder1/github-readme-streak-stats@v1.0.0
        with:
          username: "tononjacopo"
          theme: dark
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Aggiornate statistiche LeetCode" || exit 0
          git push
