name: Update LeetCode Stats
on:
  schedule:
    - cron: "0 0 * * *"  # Aggiorna ogni giorno a mezzanotte
  workflow_dispatch:  # Permette di eseguirlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch LeetCode Stats
        uses: anuraghazra/leetcode-stats@master
        with:
          username: "tononjacopo"
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Aggiornate statistiche LeetCode" || exit 0
          git push
